"""add_user_id_to_workflow_binding

Revision ID: 77eb29d86bb3
Revises: d1bb7b20fe56
Create Date: 2025-11-27 02:30:40.882449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77eb29d86bb3'
down_revision = 'd1bb7b20fe56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_bindings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('workflow_bindings_function_key_key', 'workflow_bindings', type_='unique')
    op.drop_constraint('workflow_bindings_workflow_id_key', 'workflow_bindings', type_='unique')
    op.create_foreign_key(None, 'workflow_bindings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_bindings', type_='foreignkey')
    op.create_unique_constraint('workflow_bindings_workflow_id_key', 'workflow_bindings', ['workflow_id'])
    op.create_unique_constraint('workflow_bindings_function_key_key', 'workflow_bindings', ['function_key'])
    op.drop_column('workflow_bindings', 'user_id')
    # ### end Alembic commands ###

