"""add_category_to_workflow

Revision ID: d1bb7b20fe56
Revises: 5f90587d8c06
Create Date: 2025-11-27 01:53:45.420243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bb7b20fe56'
down_revision = '5f90587d8c06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('category', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'category')
    # ### end Alembic commands ###

